# Generated by Django 5.1.4 on 2025-01-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_rename_stars_review_grade_alter_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='grade',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '* *'), (3, '* * *'), (4, '* * * *'), (5, '* * * * *')], default=1),
        ),
    ]
